[project]
name = "biodiversity"
version = "1.2.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["biodiversity*"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
extend-select = ["E", "F", "W"]

[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

